# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: dcm4chee2/db:latest
    restart: always
    environment:
      POSTGRES_USER: pacsuser
      POSTGRES_PASSWORD: pacspassword
      POSTGRES_DB: pacsdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=pacsuser --dbname=pacsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  dcm4chee2:
    image: dcm4chee2/pacs:latest
    # restart: always
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PGHOST: db
      PGUSER: pacsuser
      PGPASSWORD: pacspassword
    # command: /bin/bash

    