# Use postgres/example user/password credentials
version: '3.1'

services:

  pgadmin:
    image: dpage/pgadmin4:6.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "8090:80"
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready --username=pacsuser --dbname=pacsdb"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

    